urls:
- http://conference.wirelessinnovation.org
- http://cwit.ca/2026
- http://eeccis.ub.ac.id
- http://i4cs-conference.org
- http://iaict.org
- http://icp2026.photonicssociety.org.my
- http://icsigsys.info
- http://icufn.org
- http://iiscc.net
- http://iswcs.org/iswcs2026
- http://iwcmc.net/2026
- http://smartnets.ieee.tn
- http://voyager.ce.fit.ac.jp/conf/cisis/2026
- http://voyager.ce.fit.ac.jp/conf/imis/2026
- http://wons-conference.org
- http://www.ai-medtech.eu
- http://www.bmsb2026.com
- http://www.comsnets.org
- http://www.ieee-icce.org
- http://www.ietcint.com
- http://www.isncc-conf.org
- http://www.iwcit.com
- http://www.mecoconference.me
- http://www.unet-conf.org
- http://www.wocc.org
- https://2026-ieee-rfid-ta.esat.kuleuven.be
- https://2026.giis-conference.org
- https://2026.iccspa.org
- https://2026.ieeecaribcon.org
- https://2026.softcom.fesb.unist.hr
- https://arci-conference.com
- https://asiaccs2026.cse.iitkgp.ac.in/workshops
- https://atoms-conferences.org
- https://bioxplore.umy.ac.id
- https://blackseacom2026.ieee-blackseacom.org
- https://ccci.udg.edu
- https://cits.udg.edu
- https://conf-imns.org
- https://conferences.tiu.edu.iq/iec
- https://cs-conferences.acadiau.ca/ant-26
- https://cymaen.org
- https://difcon.mmu.edu.my
- https://dyspan2026.ieee-dyspan.org
- https://easychair.org/conferences?conf=bdsc2026
- https://ectidamtncon2026.payap.ac.th
- https://elib.its.ac.id/conf/isitia/main
- https://en.g6gconference.com
- https://eng.buu.ac.th/ecti-con2026
- https://eng.ed.ac.uk/csndsp-2026
- https://ewh.ieee.org/conf/stem
- https://healthcom2025.ieee-healthcom.org
- https://hpsr2026.ieee-hpsr.org
- https://ic.gulf.edu.sa/icoesat2
- https://icabcd.org
- https://icadeis.org
- https://icbc2026.ieee-icbc.org
- https://icbir.tni.ac.th
- https://icc2025.ieee-icc.org
- https://icca-conf.info/icca25
- https://iccerec.com
- https://iccsp.apec.edu.in
- https://icdsg.org/2026
- https://icicyta.telkomuniversity.ac.id/2026
- https://icoeins.telkomuniversity.ac.id
- https://ict2026thessaloniki.org
- https://ieee-iscc.computer.org/2026
- https://ieee-vnc.org
- https://ieeeieacon.org
- https://ieeesm.org
- https://ieeesoutheastcon.org
- https://impgroup.org/imp-conference-2026
- https://incosst.polteksci.ac.id
- https://infocom2025.ieee-infocom.org
- https://iscisc2025.sbu.ac.ir/fa
- https://itc-cscc2026.ecti-thailand.org
- https://jcsse2026.org
- https://lanman2025.ieee-lanman.org
- https://lanman2026.ieee-lanman.org
- https://litis.univ-lehavre.fr/sand2026
- https://mcsoc-forum.org
- https://mecoconference.me/ss-cpsiot2026
- https://menacomm.org
- https://mnc2026.ieee-ims.org
- https://mrw2026.org
- https://nacdc.in
- https://netcompute.org
- https://netsoft2026.ieee-netsoft.org
- https://nordic-digihealth.com
- https://ondm2026.de
- https://phmconf.org
- https://pimrc2025.ieee-pimrc.org
- https://pimrc2026.ieee-pimrc.org
- https://portale2.unime.it/smartcomp2026
- https://sgc2025.ieee-smartgridcomm.org
- https://siml.ums.ac.id
- https://sips2026.org
- https://sites.google.com/view/holistic6g
- https://splitech.org
- https://vnit.ac.in/ISAMET-26
- https://voyager.ce.fit.ac.jp/conf/3pgcic/2026
- https://voyager.ce.fit.ac.jp/conf/bwcca/2026
- https://voyager.ce.fit.ac.jp/conf/incos/2026
- https://voyager.ce.fit.ac.jp/conf/nbis/2026
- https://wcnc2026.ieee-wcnc.org
- https://wiopt2026.github.io
- https://www.apcap2026.org
- https://www.cicet.org
- https://www.comsoc.org
- https://www.eucnc.eu
- https://www.iccci.org
- https://www.icccm.org
- https://www.icet.net
- https://www.icin-conference.org
- https://www.icmmts.org/home
- https://www.icsip.org
- https://www.icsp.org
- https://www.ieee-meditcom.org
- https://www.ieee-netsoft.org
- https://www.ieee.org
- https://www.ieeespace.org
- https://www.ieeewamicon.org
- https://www.itu.int/en/ITU-T/academia/kaleidoscope/Pages/default.aspx
- https://www.kios.ucy.ac.cy/drcn2026
- https://www.mtc.edu.eg/mtcwebsite/Conference.aspx
- https://www.overturetool.org/workshops/24th-overture-workshop.html
- https://www.wcse.us
- https://www.wincom-conf.org/WINCOM_2026
